---
title: "Week 2 Case study desciptive analytics"
format: html
editor: visual
---

```{r, load libraries}
#| include: TRUE
#| echo: TRUE
# see more about chunk options, such as include and echo,  at https://quarto.org/docs/computations/execution-options.html
library(tidyverse)
```

# Exercise 1

To load the data in R environment, download the data from Canvas to your computer and use the command `load` as below. Do not forget to substitute the path to the file to the path to the file on YOUR computer

```{r load bike data}
# Do not forget to substitute the path to the file to the path to the file on YOUR computer.
# on Windows, the paths might look like  "C:\\Users\\YourUsername\\Documents\\bike.Rdata"
# on MAC OS, the paths look like "/Users/YourUsername/Documents/bike.Rdata"
load("/Users/gote0002/Documents/GitHub/Business-Analytics/Data sets/Bike rental/bike.Rdata")
```

```{r}
bike %>%
  ggplot() +
  geom_point(aes(x = dteday, y = total)) +
  labs(title = "Bike Rentals per day", x = "Day", y = "Number of Rentals") +
  theme_minimal()
```

# Exercise 2

```{r}
bike %>%
  ggplot(aes(x = tempC, y = total)) +
  geom_point() +
  # geom_smooth(method = 'lm') +
  labs(title = "Bike Rentals vs. Temperature", x = "Temperature, C", y = "Number of Rentals")
```

# Exercise 3

Boxplots

```{r}
bike %>%
  ggplot() +
  geom_boxplot(aes(y = member)) +
  labs(title = "Bike Rentals: Members", x = "User Type", y = "Number of Rentals")

bike %>%
  ggplot() +
  geom_boxplot(aes(y = nonmember)) +
  labs(title = "Bike Rentals: Nonmembers", x = "User Type", y = "Number of Rentals")
# Another possibility is to plot the boxplots on the same plot
bike_long <- bike %>%
  pivot_longer(cols = c(member, nonmember), names_to = "customer_type", values_to = "number_of_rentals")
bike_long %>%
  ggplot() +
  geom_boxplot(aes(x = customer_type, y = number_of_rentals)) +
  labs(title = "Bike Rentals", x = "Customer Type", y = "Number of Rentals") +
  theme_bw()
```

Histograms

```{r}
bike_long %>%
  ggplot() +
  geom_histogram(aes(x = number_of_rentals), bins = 30) +
  facet_wrap(~customer_type) +
  labs(title = "Bike Rentals", x = "Number of rentals", y = "Day count") +
  theme_minimal()

bike_long %>%
  ggplot() +
  geom_histogram(aes(x = number_of_rentals, col = customer_type), bins = 30) +
  labs(title = "Bike Rentals", x = "Customer Type", y = "Number of Rentals") +
  theme_minimal()
```

Summaries

```{r}
summary(bike$member)
summary(bike$nonmember)
```

# Exercise 4

```{r}
bike %>%
  pivot_longer(cols = c(member, nonmember), names_to = "customer_type", values_to = "number_of_rentals") %>%
  ggplot(aes(x = tempC, y = number_of_rentals, col = customer_type)) +
  facet_wrap(~season) +
  geom_point() +
  theme_minimal() + 
  labs(title = "Bike Rentals vs. Temperature by season and customer type", 
       x = "Temperature, C", 
       y = "Number of Rentals",
       col = "Customer type" )+
  theme(legend.position = "bottom")  # This moves the legend to the bottom

# bike %>%
#   pivot_longer(cols = c(member, nonmember), names_to = "customer_type", values_to = "number_of_rentals") %>%
#   ggplot(aes(x = tempC, y = number_of_rentals)) +
#   facet_grid(customer_type~season) +
#   geom_point() +
#   theme_minimal() + 
#   labs(title = "Bike Rentals vs. Temperature by season and customer type", 
#        x = "Temperature, C", 
#        y = "Number of Rentals",
#        col = "Customer type" )  
```

# Exercise 5

```{r}
bike %>%
  count(weathersit)

bike %>%
  ggplot() +
  geom_bar(aes(x = weathersit))
```
